<template>
  <div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
    <div>这是回到顶部页面2</div>
  </div>
</template>
<script>
export default {
  name: 'BackTopTwo',
  components: {},
}
</script>
